### ISSUE TITLE
ECS CPU ve RAM optimizasyonu

### ISSUE THREAD

**Issue by ferhatbostanci** [acikkaynak/deprem-yardim-cloud-infra#31]
Şu anda tüm ECS'lerde 2 CPU ve 4 GB RAM bulunmakta bu nedenle son 1 haftanın metriklerine bakılarak container CPU ve RAM leri optimize edilecek.

**Comment by aecceyhan** [comment]
Ram ve CPU task-defination.json dosyalarından kolayca ayarlanabiliyor. FYI

https://github.com/acikkaynak/eczane-backend/blob/main/task-definition.json



![Image](https://user-images.githubusercontent.com/17556123/218339914-16ebd1e9-d6a2-48b4-aa81-e9b0316956e7.png)
