### ISSUE TITLE
go consumer resource azaltılması

### ISSUE THREAD

**Issue by mstrYoda** [acikkaynak/deprem-yardim-cloud-infra#56]
go consumer şu an 4gb ram resource verilmiş bu kadar resource ihtiyacı bulunmuyor max 1 gb olacak şekilde ayarlanabilir

**Comment by aecceyhan** [comment]
https://github.com/acikkaynak/deprem-yardim-backend-go/pull/140 PR kabul edilmesi bekleniyor.
