### ISSUE TITLE
Veri toplama frontend

### ISSUE THREAD

**Issue by kaanozbudak** [acikkaynak/deprem-yardim-cloud-infra#57]
https://github.com/acikkaynak/veri-toplama-frontend
nginx ayağa kalkıyordu en son, bi türlü çalışmadı, uçtan uca tf github td ve ci cd süreçleriyle prod'a açılacak cc: #GoldenPuppet#0019

**Comment by MustafaCQN** [comment]
@ferhatbostanci herhangi bir gelisme oldu mu acaba? nginx ayarlari yapilmasi gerekiyordu

https://veri-toplama.afetharita.com/ sitesine gidince bu cevap geliyor

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to [nginx.org](https://nginx.org/).
Commercial support is available at [nginx.com](https://nginx.com/).

Thank you for using nginx.

**Comment by ferhatbostanci** [comment]
https://veri-toplama.afetharita.com ve https://veri-toplama-api.afetharita.com aktif edildi @MustafaCQN

**Comment by MustafaCQN** [comment]
ellerinize saglik @ferhatbostanci @kaanozbudak

**Comment by erdaltelli** [comment]
Neden değişti link? Şu anda app çalışmıyor.
