### ISSUE TITLE
bucket'ın ec2'ya mount edilmesi ve pw management'ın oradan yönetilmesi

### ISSUE THREAD

**Issue by kaanozbudak** [acikkaynak/deprem-yardim-cloud-infra#6]

**Comment by eerkunt** [comment]
Ben bundan cok emin degilim ya, complexity i arttiracak. 

userdata icinde mi yapmaya calisacagiz bunu ?

**Comment by erselbey** [comment]
Onun farkındayım abi ama bu şekilde güvenilir bir erişim olacağını düşünüyorum. Yahut env dosyalar için secret manager kullanacaksak bunu iptal edebiliriz

**Comment by eerkunt** [comment]
Bence direk secrets manager kuillanip bir tasla iki kus vuralim. Ne dersin ?

**Comment by ferhatbostanci** [comment]
Secrets manager seçildiği için kapatıyorum.
